apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "rapids.fullname" . }}-worker
  labels:
    app: {{ template "rapids.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "rapids.chart" . }}
    component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ template "rapids.name" . }}
      release: {{ .Release.Name | quote }}
      component: worker
  strategy:
    type: {{ .Values.worker.strategy.type }}
  template:
    metadata:
      labels:
        app: {{ template "rapids.name" . }}
        release: {{ .Release.Name | quote }}
        component: worker
      {{- with .Values.worker.annotations }}
      annotations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.worker.image.pullSecrets }}
      imagePullSecrets:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.mounts.volumes }}
      volumes:
        {{- . | toYaml | nindent 8}}
      {{- end }}
      containers:
        - name: {{ template "rapids.fullname" . }}-worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          args:
            - {{ .Values.worker.image.dask_worker }}
            {{- if .Values.worker.custom_scheduler_url }}
            - {{ .Values.worker.custom_scheduler_url }}
            {{- else }}
            - {{ template "rapids.fullname" . }}-scheduler:{{ .Values.scheduler.servicePort }}
            {{- end }}
            {{- if .Values.worker.resources.limits }}
            - --nthreads
            - {{ .Values.worker.threads_per_worker | default .Values.worker.resources.limits.cpu | quote }}
            - --memory-limit
            - {{ .Values.worker.resources.limits.memory | quote }}
            {{- end }}
            - --no-dashboard
            - --dashboard-address
            - {{ .Values.worker.portDashboard | quote }}
            {{- with .Values.worker.port }}
            - --worker-port
            - {{ . | quote }}
            {{- end }}
            {{- with .Values.worker.extraArgs }}
            {{ . | toYaml | nindent 12 }}
            {{- end }}
          {{- with .Values.worker.resources }}
          resources:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.worker.env }}
          env:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.worker.mounts.volumeMounts }}
          volumeMounts:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.securityContext }}
      securityContext:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.serviceAccountName }}
      serviceAccountName: {{ . | quote }}
      {{- end }}
