---
apiVersion: v1
name: rapids
version: 0.0.1-set.by.chartpress
appVersion: "22.08"
description: GPU accelerated scalable data science framework.
home: https://rapids.ai
icon:
sources:
  - https://github.com/rapidsai
maintainers:
